export default function SolutionsSection() {
  return (
      <section id="solutions" className="section solutions-section"><div className="container">
      <div className="section-intro reveal"><div><div className="eyebrow">THE RIGHT HARDWARE. THE RIGHT FIT.</div><h2>Three ways to make<br /><em>every sale count.</em></h2></div><p>A handheld for the floor. A compact counter companion. A connected fuel-and-store setup. Find the starting point that fits your day.</p></div><div className="lineup-helper reveal"><p>Not sure where to start?</p><button className="text-link" data-action="finder">Find my device <span aria-hidden={true}>↗</span></button></div>
      <div className="device-grid">
      <article className="device-card reveal"><div className="device-top"><span className="pill">ON THE MOVE</span><span className="device-index">01</span></div><div className="device-image flex-image"><img src="/images/clover-flex.png" width={426} height={357} alt="Clover Flex handheld POS" loading="lazy" /></div><div className="device-copy"><span className="device-for">RESTAURANTS · POP-UPS · MOBILE SALES</span><h3>Clover Flex</h3><p>Bring checkout to your customer. This handheld POS combines card payments, barcode scanning and a built-in receipt printer in one compact device.</p><ul><li>Tap, chip and swipe payments</li><li>Built-in printer and scanner</li><li>Portable, all-in-one checkout</li></ul><a className="device-cta" href="#contact" data-device="Clover Flex">Get a Clover Flex quote <span aria-hidden={true}>↗</span></a></div></article>
      <article className="device-card reveal"><div className="device-top"><span className="pill">AT THE COUNTER</span><span className="device-index">02</span></div><div className="device-image mini-image"><img src="/images/clover-mini-device.png" width={456} height={249} alt="Clover Mini compact countertop POS" loading="lazy" /></div><div className="device-copy"><span className="device-for">CAFÉS · BOUTIQUES · SALONS</span><h3>Clover Mini</h3><p>A capable checkout in a smaller footprint. Accept payments at your counter and bring sales and inventory into your everyday workflow.</p><ul><li>Space-saving countertop design</li><li>Contactless and chip payments</li><li>Sales and inventory tools*</li></ul><a className="device-cta" href="#contact" data-device="Clover Mini">Get a Clover Mini quote <span aria-hidden={true}>↗</span></a></div></article>
      <article className="device-card reveal"><div className="device-top"><span className="pill">FUEL + STORE</span><span className="device-index">03</span></div><div className="device-image petro-image"><img src="/images/nrs-petro-device.png" width={432} height={324} alt="NRS Petro POS bundle with register, customer display, scanner, cash drawer and printer" loading="lazy" /></div><div className="device-copy"><span className="device-for">GAS STATIONS · CONVENIENCE STORES</span><h3>NRS Petro</h3><p>Connect the forecourt with the front counter. A POS solution designed around fuel sales, convenience retail and the rhythm of shift changes.</p><ul><li>Compatible pump integration*</li><li>Fuel and in-store sales workflow</li><li>Cashier and shift reporting</li></ul><a className="device-cta" href="#contact" data-device="NRS Petro">Get an NRS Petro quote <span aria-hidden={true}>↗</span></a></div></article>
      </div><p className="product-note">*Features, software plans, connectivity and pump compatibility depend on your selected configuration. Confirm availability and pricing with PrismaTech.</p>
      </div></section>
  );
}
